apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- hpa.yaml

namespace: staging

commonLabels:
  environment: staging

replicas:
- count: 3
  name: windows-aspnet-app

images:
- name: acrdemoeastus2001.azurecr.io/windows-aspnet
  newTag: f5e3caa3cd5cfe0c445fefd633d2144f5e4fc088
