apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- hpa.yaml

namespace: staging

labels:
- pairs:
    environment: staging

replicas:
- count: 3
  name: windows-aspnet-app

images:
- name: acrdemoeastus2001.azurecr.io/windows-aspnet
  newTag: 3e2c6a438c9bb8970cd1439048c1288c2f96feb5
