# Kubernetes Deployment for Windows ASP.NET Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-aspnet-app
  namespace: default
  labels:
    app: windows-aspnet-app
    version: v1.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: windows-aspnet-app
  template:
    metadata:
      labels:
        app: windows-aspnet-app
        version: v1.0
    spec:
      # Windows node selector - ensures pods are scheduled on Windows nodes
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: aspnet-app
        image: acrdemoeastus2001.azurecr.io/windows-aspnet:v1.0
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /hello
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /hello
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      # Image pull secrets for Azure Container Registry
      imagePullSecrets:
      - name: acr-secret
---
# Kubernetes Service
apiVersion: v1
kind: Service
metadata:
  name: windows-aspnet-service
  namespace: default
  labels:
    app: windows-aspnet-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: windows-aspnet-app
---
# Horizontal Pod Autoscaler (Optional)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: windows-aspnet-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: windows-aspnet-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80