apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- pdb.yaml

namespace: production

commonLabels:
  environment: production

replicas:
- count: 5
  name: windows-aspnet-app

images:
- name: acrdemoeastus2001.azurecr.io/windows-aspnet
  newTag: a6bb57cb5658d1c97804d90f9945de6c5e7b5110
