apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- pdb.yaml

namespace: production

labels:
- pairs:
    environment: production

replicas:
- name: windows-aspnet-app
  count: 5

images:
- name: acrdemoeastus2001.azurecr.io/windows-aspnet
  newTag: v1.0