apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-infrastructure
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: aks-gitops-demo
  path: "./fluxcd/infrastructure"
  prune: true
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-applications
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: aks-gitops-demo
  path: "./environments/fluxcd"
  prune: true
  wait: false
  timeout: 5m
  dependsOn:
    - name: flux-infrastructure