apiVersion: v1
kind: Namespace
metadata:
  name: staging-flux
  labels:
    name: staging-flux
    gitops-tool: fluxcd
    environment: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-aspnet-app
  namespace: staging-flux
  labels:
    app: windows-aspnet-app
    environment: staging-flux
    gitops-tool: fluxcd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: windows-aspnet-app
  template:
    metadata:
      labels:
        app: windows-aspnet-app
        environment: staging-flux
        gitops-tool: fluxcd
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: aspnet-app
        image: acrdemoeastus2001.azurecr.io/windows-aspnet:02bff8b5b0787d7e83706c77178dfe0dcaf12d7e
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Staging"
        - name: GITOPS_TOOL
          value: "FluxCD"
---
apiVersion: v1
kind: Service
metadata:
  name: windows-aspnet-service
  namespace: staging-flux
  labels:
    app: windows-aspnet-app
    environment: staging-flux
    gitops-tool: fluxcd
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: windows-aspnet-app
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: windows-aspnet-hpa
  namespace: staging-flux
  labels:
    app: windows-aspnet-app
    environment: staging-flux
    gitops-tool: fluxcd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: windows-aspnet-app
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70