name: Promote and Deploy to Staging/Production

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      image_tag:
        description: 'Image tag to deploy (leave empty to build new)'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

env:
  REGISTRY_NAME: acrdemoeastus2001
  IMAGE_NAME: windows-aspnet

jobs:
  determine-image:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.tag }}
      
    steps:
    - name: 'Determine image tag to deploy'
      id: set-tag
      run: |
        if [[ "${{ github.event.inputs.image_tag }}" != "" ]]; then
          # Use provided image tag
          TAG="${{ github.event.inputs.image_tag }}"
          echo "Using provided image tag: $TAG"
        elif [[ "${{ github.event_name }}" == "release" ]]; then
          # Use release tag
          TAG="${{ github.event.release.tag_name }}"
          echo "Using release tag: $TAG"
        else
          # Use latest commit SHA from main branch (reuse existing image)
          TAG="${{ github.sha }}"
          echo "Using commit SHA (reusing existing image): $TAG"
        fi
        
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "Final image tag: $TAG"

    - name: 'Verify image exists in ACR'
      run: |
        echo "🔍 Verifying image exists in ACR..."
        echo "Image to deploy: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.tag }}"
        echo "✅ Promoting existing image instead of rebuilding"

  deploy-environment:
    needs: [determine-image]
    runs-on: ubuntu-latest
    if: always() && !cancelled()
    
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: 'Setup Kustomize'
      run: |
        # Use direct binary download to avoid GitHub rate limiting
        KUSTOMIZE_VERSION="v5.3.0"
        wget -O kustomize.tar.gz "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_amd64.tar.gz"
        tar -xzf kustomize.tar.gz
        chmod +x kustomize
        sudo mv kustomize /usr/local/bin/
        kustomize version

    - name: 'Determine image tag and environment'
      id: deployment-info
      run: |
        if [[ "${{ github.event.inputs.image_tag }}" != "" ]]; then
          IMAGE_TAG="${{ github.event.inputs.image_tag }}"
        else
          IMAGE_TAG="${{ needs.determine-image.outputs.image-tag }}"
        fi
        
        if [[ "${{ github.event.inputs.environment }}" != "" ]]; then
          ENVIRONMENT="${{ github.event.inputs.environment }}"
        else
          ENVIRONMENT="production"
        fi
        
        echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
        echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
        
        echo "Deploying to: $ENVIRONMENT"
        echo "Image tag: $IMAGE_TAG"

    - name: 'Update environment manifests'
      run: |
        ENVIRONMENT="${{ steps.deployment-info.outputs.environment }}"
        IMAGE_TAG="${{ steps.deployment-info.outputs.image-tag }}"
        
        cd environments/$ENVIRONMENT
        kustomize edit set image ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:$IMAGE_TAG
        
        echo "Updated $ENVIRONMENT environment with image: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:$IMAGE_TAG"

    - name: 'Create Pull Request for Production'
      if: steps.deployment-info.outputs.environment == 'production'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: |
          🚀 Deploy ${{ steps.deployment-info.outputs.image-tag }} to Production
          
          - Environment: Production
          - Image Tag: ${{ steps.deployment-info.outputs.image-tag }}
          - Triggered by: ${{ github.event_name }}
        title: 'Deploy ${{ steps.deployment-info.outputs.image-tag }} to Production'
        body: |
          ## Production Deployment Request
          
          **Image Tag:** `${{ steps.deployment-info.outputs.image-tag }}`
          **Environment:** Production
          **Triggered by:** ${{ github.event_name }}
          
          ### Changes
          - Updates production environment to use image: `${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.deployment-info.outputs.image-tag }}`
          
          ### Deployment Process
          1. Review and approve this PR
          2. Merge to deploy to production
          3. Monitor deployment in ArgoCD UI
          
          ### Rollback
          If rollback is needed, revert this PR or update the image tag in the production manifest.
        branch: deploy-production-${{ steps.deployment-info.outputs.image-tag }}
        delete-branch: true

    - name: 'Direct commit for Staging'
      if: steps.deployment-info.outputs.environment == 'staging'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add environments/staging/
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🚀 Deploy ${{ steps.deployment-info.outputs.image-tag }} to Staging
          
          - Environment: Staging
          - Image Tag: ${{ steps.deployment-info.outputs.image-tag }}
          - Triggered by: ${{ github.event_name }}
          - Workflow: ${{ github.workflow }}"
          
          git push origin main
          echo "Successfully deployed to staging environment"
        fi

  notify-teams:
    needs: [determine-image, deploy-environment]
    runs-on: ubuntu-latest
    if: always() && !cancelled()
    
    steps:
    - name: 'Notify deployment status'
      run: |
        if [[ "${{ needs.deploy-environment.result }}" == "success" ]]; then
          echo "✅ Deployment completed successfully!"
          echo "Environment: ${{ github.event.inputs.environment || 'production' }}"
          echo "Image: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ needs.determine-image.outputs.image-tag }}"
        else
          echo "❌ Deployment failed!"
          echo "Please check the workflow logs for more details."
        fi