name: Release and Deploy to Production

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      image_tag:
        description: 'Image tag to deploy (leave empty to build new)'
        required: false
        type: string

env:
  REGISTRY_NAME: acrdemoeastus2001
  IMAGE_NAME: windows-aspnet

jobs:
  build-release:
    runs-on: windows-latest
    if: github.event.inputs.image_tag == '' || github.event_name == 'release'
    
    outputs:
      image-tag: ${{ steps.set-tag.outputs.tag }}
      
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v4

    - name: 'Setup .NET'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore and build'
      run: |
        dotnet restore
        dotnet build --no-restore --configuration Release
      working-directory: ./aspnet-demo

    - name: 'Login to Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: 'Set release tag'
      id: set-tag
      run: |
        if ("${{ github.event_name }}" -eq "release") {
          $tag = "${{ github.event.release.tag_name }}"
        } else {
          $tag = "v1.0.${{ github.run_number }}"
        }
        
        echo "tag=$tag" >> $env:GITHUB_OUTPUT
        echo "RELEASE_TAG=$tag" >> $env:GITHUB_ENV
        echo "Release tag: $tag"

    - name: 'Build and push release image'
      run: |
        $releaseImage = "${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.RELEASE_TAG }}"
        $latestImage = "${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest"
        
        echo "Building release image: $releaseImage"
        docker build -t $releaseImage -t $latestImage -f Dockerfile .
        
        docker push $releaseImage
        docker push $latestImage
        
        echo "Successfully pushed release image: $releaseImage"
      working-directory: ./aspnet-demo

  deploy-environment:
    needs: [build-release]
    runs-on: ubuntu-latest
    if: always() && !cancelled()
    
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: 'Setup Kustomize'
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin/

    - name: 'Determine image tag and environment'
      id: deployment-info
      run: |
        if [[ "${{ github.event.inputs.image_tag }}" != "" ]]; then
          IMAGE_TAG="${{ github.event.inputs.image_tag }}"
        else
          IMAGE_TAG="${{ needs.build-release.outputs.image-tag }}"
        fi
        
        if [[ "${{ github.event.inputs.environment }}" != "" ]]; then
          ENVIRONMENT="${{ github.event.inputs.environment }}"
        else
          ENVIRONMENT="production"
        fi
        
        echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
        echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
        
        echo "Deploying to: $ENVIRONMENT"
        echo "Image tag: $IMAGE_TAG"

    - name: 'Update environment manifests'
      run: |
        ENVIRONMENT="${{ steps.deployment-info.outputs.environment }}"
        IMAGE_TAG="${{ steps.deployment-info.outputs.image-tag }}"
        
        cd environments/$ENVIRONMENT
        kustomize edit set image ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:$IMAGE_TAG
        
        echo "Updated $ENVIRONMENT environment with image: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:$IMAGE_TAG"

    - name: 'Create Pull Request for Production'
      if: steps.deployment-info.outputs.environment == 'production'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: |
          🚀 Deploy ${{ steps.deployment-info.outputs.image-tag }} to Production
          
          - Environment: Production
          - Image Tag: ${{ steps.deployment-info.outputs.image-tag }}
          - Triggered by: ${{ github.event_name }}
        title: 'Deploy ${{ steps.deployment-info.outputs.image-tag }} to Production'
        body: |
          ## Production Deployment Request
          
          **Image Tag:** `${{ steps.deployment-info.outputs.image-tag }}`
          **Environment:** Production
          **Triggered by:** ${{ github.event_name }}
          
          ### Changes
          - Updates production environment to use image: `${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.deployment-info.outputs.image-tag }}`
          
          ### Deployment Process
          1. Review and approve this PR
          2. Merge to deploy to production
          3. Monitor deployment in ArgoCD UI
          
          ### Rollback
          If rollback is needed, revert this PR or update the image tag in the production manifest.
        branch: deploy-production-${{ steps.deployment-info.outputs.image-tag }}
        delete-branch: true

    - name: 'Direct commit for Staging'
      if: steps.deployment-info.outputs.environment == 'staging'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add environments/staging/
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🚀 Deploy ${{ steps.deployment-info.outputs.image-tag }} to Staging
          
          - Environment: Staging
          - Image Tag: ${{ steps.deployment-info.outputs.image-tag }}
          - Triggered by: ${{ github.event_name }}
          - Workflow: ${{ github.workflow }}"
          
          git push
          echo "Successfully deployed to staging environment"
        fi

  notify-teams:
    needs: [build-release, deploy-environment]
    runs-on: ubuntu-latest
    if: always() && !cancelled()
    
    steps:
    - name: 'Notify deployment status'
      run: |
        if [[ "${{ needs.deploy-environment.result }}" == "success" ]]; then
          echo "✅ Deployment completed successfully!"
          echo "Environment: ${{ needs.deploy-environment.outputs.environment }}"
          echo "Image: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ needs.build-release.outputs.image-tag }}"
        else
          echo "❌ Deployment failed!"
          echo "Please check the workflow logs for more details."
        fi