name: Auto-Update Development Environment

on:
  workflow_run:
    workflows: ["Build and Deploy Windows ASP.NET to ACR"]
    types:
      - completed
    branches: [ main ]

permissions:
  contents: write

env:
  REGISTRY_NAME: acrdemoeastus2001
  IMAGE_NAME: windows-aspnet

jobs:
  auto-update-development:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: 'Get workflow run info'
      id: workflow-info
      run: |
        # Get the commit SHA from the triggering workflow
        COMMIT_SHA="${{ github.event.workflow_run.head_sha }}"
        echo "commit-sha=$COMMIT_SHA" >> $GITHUB_OUTPUT

    - name: 'Checkout repository'
      uses: actions/checkout@v4
      with:
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: 'Setup Kustomize'
      run: |
        # Use direct binary download to avoid GitHub rate limiting
        KUSTOMIZE_VERSION="v5.3.0"
        wget -O kustomize.tar.gz "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_amd64.tar.gz"
        tar -xzf kustomize.tar.gz
        chmod +x kustomize
        sudo mv kustomize /usr/local/bin/
        kustomize version

    - name: 'Setup Git'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Actions"
        
        # Ensure we're on main branch
        git checkout main
        git pull origin main

    - name: 'Update development environment'
      run: |
        cd environments/development
        
        # Update the image tag
        kustomize edit set image ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.workflow-info.outputs.commit-sha }}
        
        echo "Updated development environment with image: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.workflow-info.outputs.commit-sha }}"
        
        # Show the changes
        git diff

    - name: 'Commit and Push Changes'
      run: |
        git add environments/development/
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🚀 Auto-update development environment to ${{ steps.workflow-info.outputs.commit-sha }}
          
          - Updated by: GitHub Actions (Auto-deployment)
          - Triggering workflow: ${{ github.event.workflow_run.name }}
          - Run ID: ${{ github.event.workflow_run.id }}
          - Image: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.workflow-info.outputs.commit-sha }}
          
          This commit triggers ArgoCD to automatically sync the development environment."
          
          git push origin main
          echo "✅ Successfully updated development environment manifest"
        fi